---
title: "05: ggplot"
author: "Bryshal Moore & Hannah Houts"
date: "`r Sys.Date()`"
output: html_document
---
## Hannah notes:
- make a scatter plot of data
- look for vegan stuff


```{r}
library(tidyverse)

covariates <- read_tsv("data/FWS_covariates.txt")
abundances <- read_tsv("data/FWS_OTUs.txt")%>% 
  rename(taxonomy = `...1`)
```



```{r}
if (!requireNamespace("vegan", quietly = TRUE)) {
     install.packages("vegan")
}
library(vegan)

    # makes a table in the form of a matrix, where every value in the table is numeric 
abund_matrix <- as.matrix(
                          abundances_wide_tax %>% 
                          select(!sample) # eliminates the sample column, which is not numeric.  
                          )

distances <- vegdist(abund_matrix, method = "euclidean") # calculates the distances between samples in 387 dimensions


pcoa_plotting_data <- cmdscale(distances, eig= TRUE, k=2) # reduces dimensions 
                    # cmd stands for classical multidimensional scaling

pcoa_point_data <- as.data.frame(pcoa_plotting_data$points) # extracts plottable x,y coordinates from PCoA plot

pcoa_point_data$sample <- NA # add a new empty column
pcoa_point_data$sample <- abundances_wide_tax$sample  # fill that column with contents of sample column from the abundances_wide_tax table


covariates <- covariates %>% 
  rename(sample=SampleName) 

pcoa_w_metadata <- inner_join(pcoa_point_data, covariates, by = "sample") # merges the covariates table with the pcoa table


pcoa_w_metadata # take a peek at the final table, then we will plot!
```

```{r}
#Plot by Location
ggplot(pcoa_w_metadata,
       aes(
         x=V1, 
         y=V2, 
         color = Location
           )
       ) + 
  geom_point(size = 3, alpha = .5) +
  # geom_text_repel() +
  xlab("PCoA 1") +
  ylab("PCoA 2") 

```

```{r}
#Plot by season
ggplot(pcoa_w_metadata,
       aes(
         x=V1, 
         y=V2, 
         color = Season
           )
       ) + 
  geom_point(size = 3, alpha = .5) +
  # geom_text_repel() +
  xlab("PCoA 1") +
  ylab("PCoA 2") 

```

Great work!







```{r}
abundances %>% 
  across

```

```{r}
library(tidyverse)
otus <- read_tsv("data/FWS_OTUs.txt")
otus %>%
  rename("taxonomy" = 1) %>%
  pivot_longer(-1) %>%
  separate(name, c("where", "when"), remove = F) %>%
  group_by(where, when) %>%
  mutate(when = factor(when, 
                       levels = c("Jan", "Feb", "May", "Jun", "Jul", "Aug"))) %>%
  filter(taxonomy == "Bacteria;Proteobacteria;Betaproteobacteria;Burkholderiales;Burkholderiaceae;Ralstonia") %>% 
  mutate(relative_abundance = value/sum(value)) %>%
  ggplot(aes(x = name, 
             y = relative_abundance, 
             col = when)) + 
  geom_jitter(width = 0) +
  ylab("Relative\nabundance") + 
  xlab("") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```


```{r}
otus %>%
  rename("taxonomy" = 1) %>%
  pivot_longer(-1) %>%
  mutate(relative_abundance = value/sum(value)) %>%
  filter(taxonomy %in% c("Bacteria;Cyanobacteria;Cyanobacteria;SubsectionIV;Unassigned;Anabaena", 
                         "Bacteria;Proteobacteria;Betaproteobacteria;Burkholderiales;Burkholderiaceae;Ralstonia")) %>% 
  select(-value) %>%
  pivot_wider(names_from = taxonomy, 
              values_from = relative_abundance) %>%
  rename("Cyanobacteria" = 2, 
         "Proteobacteria" = 3) %>%
  ggplot(aes(x = `Cyanobacteria`, 
             y = `Proteobacteria`,)) + 
  geom_point() +
  xlab("Amy's fav Cyanobacteria\nabundance") + 
  ylab("Amy's fav Proteobacteria\nabundance") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

```

